project:
  type: website
  resources:
    - "index.html"

website:
  favicon: img/jaime-blurry-small-300h.png
  title: "Jaime Ruiz Serra"
  site-url: https://jaime.rs
  description: "Jaime Ruiz Serra's personal website"
  navbar:
    title: false
    left:
      - text: Home
        href: /
      - text: Blog
        href: /posts
  page-footer:
    border: false
    left: "Find me on [Scholar](https://scholar.google.com/citations?user=qkmyBJYAAAAJ), [LinkedIn](https://linkedin.com/in/RuizSerra), [GitHub](https://github.com/RuizSerra), [Goodreads](https://www.goodreads.com/ruizserra)"
    right: "Â© 2026 [Jaime Ruiz Serra](/)"
  # twitter-card:
  #   site: "@JRuizSerra"
  #   creator: "@JRuizSerra"
  open-graph: true
  google-analytics: "G-K8NCEFDJY2"
  # comments:
  #   hypothesis: 
  #     theme: clean
  #     openSidebar: false

format:
  html:
    theme: 
      - default
      - styles.scss
      # light: [default, styles.scss]
      # dark: darkly
    # css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-float: true
    toc-smooth-scroll: true
    toc-highlight: true
    toc-title: Contents
    email-obfuscation: javascript
    smooth-scroll: true
    highlight-style: gruvbox
    include-in-header:
      - _custom-head.html

